id: P7852DB62
initial_creation_type: input
source_metadata:
  title: Chöje Lingpa Series
  language: en
  description: 'Texts by and about the treasure-revealer Chöjé Lingpa (chos rje gling
    pa, 1682–1720):'
  volume:
    f08d6931e9eb4956a95775b5b14ae1d7:
      title: 'The New Glorious Bestower of Immortality: A Long-Life Practice and Empowerment
        that Unites the Oral, Treasure and Visionary Teachings'
      parent: Longevity
    0af2574332394f64958b1e998cfcb63d:
      title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
        Practice that Unites the Oral, Treasure and Visionary Teachings
      parent: Longevity
created_at: '2022-02-28T22:44:31.893780'
last_modified_at: '2022-02-28T22:44:31.893786'
